name: Build

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-11]
    env:
      GITHUB_TOKEN: ${{ secrets.DRAFT_TOKEN }}
      FEEDZ_SOURCE: "https://f.feedz.io/wormiecorp/packages/nuget/index.json"
      FEEDZ_API_KEY: ${{ secrets.FEEDZ_API_KEY }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"
      WYAM_DEPLOY_BRANCH: "gh-pages"

    steps:
      - uses: actions/checkout@v2.7.0
        if: ${{ github.event.action != 'published' }}
        with:
          fetch-depth: 0
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('build.cake') }}
      - name: Build project (Windows)
        if: matrix.os == 'windows-2019'
        run: ./build.ps1 --verbosity=Diagnostic --target=CI
        shell: pwsh
      - name: Build project (Unix)
        if: matrix.os != 'windows-2019'
        run: ./build.sh --verbosity=Diagnostic --target=CI
