name: Publish Documentation

on:
  workflow_dispatch:

jobs:
  publish-docs:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"
      WYAM_DEPLOY_BRANCH: "gh-pages"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout the requested branch
        uses: actions/checkout@v2.7.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.ref }}
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-doc-tools-${{ hashFiles('build.cake') }}
      - name: Forcing documentation publishing
        run: ./build.sh --target=Force-Publish-Documentation --verbosity=Diagnostic
